default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: black
        name: format-code
        entry: python -m
        args:
          - black
        language: system
        types: [python]
        exclude: vendor/

  - repo: local
    hooks:
      - id: isort
        name: sort-imports
        entry: python -m
        args: ["isort", "--profile", "black"]
        language: system
        types: [python]
        exclude: vendor/

  - repo: local
    hooks:
      - id: pylint
        name: lint-code
        entry: python -m
        args:
          - pylint
        language: system
        types: [python]
        exclude: vendor/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=50000"]
        exclude: vendor/

  - repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0
    hooks:
      - id: nb-ensure-clean
        name: nb-ensure-clean
        files: \.ipynb$
        exclude: \_ko.ipynb$|vendor/

  - repo: https://github.com/woile/commitizen
    rev: v2.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
